// web/src/lib/errors.js
// 后端 SavedModelEditError 与 HTTP 共用错误码 → 中文文案。
// 未识别码退到原始 message。

const TABLE = {
  COMPUTER_USE_SETTINGS_UNSUPPORTED: '当前后台服务不支持电脑操控，请更新 ACECode 并重启后重试',
  COMPUTER_USE_SETTINGS_AUTH_REQUIRED: '后台连接认证已失效，请重新连接 ACECode 后重试',
  COMPUTER_USE_SETTINGS_UNAVAILABLE: '后台服务暂不可用，请稍后重试',
  COMPUTER_USE_PLATFORM_UNSUPPORTED: '电脑操控目前仅支持 Windows',
  MODEL_ORDER_CONFLICT: '模型列表已发生变化，请刷新后重新排序',
  IMAGE_SETTINGS_UNSUPPORTED: '当前后台服务不支持图像生成，请更新 ACECode 并重启后重试',
  SUMMARY_SETTINGS_UNSUPPORTED: '当前后台服务不支持摘要生成，请更新 ACECode 并重启后重试',
  SUMMARY_SETTINGS_AUTH_REQUIRED: '后台连接认证已失效，请重新连接 ACECode 后重试',
  SUMMARY_SETTINGS_UNAVAILABLE: '后台服务暂不可用，请稍后重试',
  SUMMARY_MODEL_REQUIRED: '请选择摘要模型',
  IMAGE_SETTINGS_AUTH_REQUIRED: '后台连接认证已失效，请重新连接 ACECode 后重试',
  IMAGE_SETTINGS_UNAVAILABLE: '后台服务暂不可用，请稍后重试',
  IMAGE_COST_CONFIRMATION_REQUIRED: '测试会消耗额度，请从生成测试图片按钮发起',
  IMAGE_TEST_BUSY: '已有测试图片正在生成，请稍候',
  IMAGE_NOT_CONFIGURED: '请先填写 API 地址和 Key，或选择可用的模型连接',
  IMAGE_QUOTA_ERROR: '图像服务额度不足或请求过于频繁，请检查额度后重试',
  IMAGE_TEST_FAILED: '生成测试图片失败，请检查连接和模型名称',
  TOOL_REWRITES_UNSUPPORTED: '当前后台服务不支持工具重写，请更新 ACECode 并重启后重试',
  TOOL_REWRITES_AUTH_REQUIRED: '后台连接认证已失效，请重新连接 ACECode 后重试',
  TOOL_REWRITES_UNAVAILABLE: '后台服务暂不可用，请稍后重试',
  APPLY_FAILED: '配置已保存但未能生效，请重试',
  SECURITY_UNSUPPORTED: '当前后台服务不支持安全中心，请更新 ACECode 并重启后重试',
  SECURITY_AUTH_REQUIRED: '后台连接认证已失效，请重新连接 ACECode 后重试',
  SECURITY_UNAVAILABLE: '后台服务暂不可用，请稍后重试',
  AUDIT_UNAVAILABLE: '审计日志在当前后台进程中不可用（数据目录不可写或未初始化）',
  AUDIT_QUERY_FAILED: '读取审计日志失败',
  AUDIT_CLEAR_FAILED: '清空审计日志失败',
  INVALID_NAME:      '名字不能为空',
  RESERVED_NAME:     '名字以 ( 开头是系统保留',
  NAME_TAKEN:        '已存在同名条目',
  UNKNOWN_PROVIDER:  '不支持的 provider 类型',
  MISSING_MODEL:     '请填写 model',
  MISSING_BASE_URL:  '该 provider 必须填写 base_url',
  INVALID_API_KEY:   '该 provider 的 API key 不能为空',
  INVALID_API_PROTOCOL: 'API 协议无效，请选择 Chat Completions 或 Responses',
  INVALID_CONTEXT_WINDOW: '上下文窗口必须是大于 0 的数字',
  INVALID_CAPABILITY: '模型能力标签无效',
  INVALID_REQUEST_HEADER: '自定义请求头 JSON 无效',
  NOT_FOUND:         '该模型已不存在,请刷新',
  IN_USE_AS_DEFAULT: '该模型正在使用中,稍后再试',
  MODEL_IN_USE:      '该模型正在被运行中的会话使用,稍后再试',
  PERSIST_FAILED:    '配置写盘失败',
  BAD_JSON:          '请求格式错误',
  BAD_REQUEST:       '请求参数错误',
  FEEDBACK_TOO_LONG: '反馈内容不能超过 10000 字',
  DEVICE_CODE_FAILED: '无法获取 GitHub 验证码',
  COPILOT_AUTH_REQUIRED: '请先登录 Copilot',
  COPILOT_TOKEN_EXCHANGE_FAILED: 'Copilot 授权校验失败',
  COPILOT_MODELS_UNREACHABLE: '无法连接 Copilot 模型服务',
  COPILOT_MODELS_HTTP_ERROR: 'Copilot 模型服务返回错误',
  COPILOT_MODELS_BAD_JSON: 'Copilot 模型列表格式错误',
  GROK_AUTH_REQUIRED: '请先连接 Grok Coding Plan',
  GROK_DEVICE_CODE_REQUIRED: 'Grok 设备授权信息已失效，请重新连接',
  GROK_DEVICE_AUTH_UNREACHABLE: '无法连接 xAI 设备授权服务',
  GROK_DEVICE_AUTH_FAILED: '无法获取 Grok 验证码',
  GROK_TOKEN_BAD_JSON: 'Grok 授权响应格式错误',
  GROK_AUTH_UNREACHABLE: '无法连接 xAI 授权服务',
  GROK_AUTH_SAVE_FAILED: 'Grok 登录成功，但凭据保存失败',
  GROK_REFRESH_FAILED: 'Grok 登录已过期，请重新连接',
  GROK_REFRESH_TOKEN_MISSING: 'Grok 登录已失效，请重新连接',
  GROK_AUTH_EXPIRED: 'Grok 登录已过期，请重新连接',
  GROK_MODELS_UNREACHABLE: '无法连接 Grok 模型服务',
  GROK_MODELS_HTTP_ERROR: 'Grok 模型服务返回错误',
  GROK_MODELS_BAD_JSON: 'Grok 模型列表格式错误',
  GROK_AUTH_DELETE_FAILED: '删除 Grok 凭据失败',
  DELETE_FAILED:     '删除凭据失败',
  // api.js 的请求超时(见 DEFAULT_REQUEST_TIMEOUT_MS)。
  TIMEOUT:           '请求超时,请重试',
};

export function lookupErrorMessage(code, fallback) {
  if (code && Object.prototype.hasOwnProperty.call(TABLE, code)) return TABLE[code];
  return fallback || code || '未知错误';
}

export const ERROR_CODES = Object.keys(TABLE);
