import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(SCRIPT_DIR, '..');
const VSCODE_ROOT = process.env.VSCODE_REPO || path.resolve(ROOT_DIR, '..', 'vscode');
const SETI_DIR = process.env.VSCODE_SETI_ICONS_DIR || path.join(VSCODE_ROOT, 'extensions', 'theme-seti', 'icons');
const EXTENSIONS_DIR = process.env.VSCODE_EXTENSIONS_DIR || path.join(VSCODE_ROOT, 'extensions');
const THEME_PATH = path.join(SETI_DIR, 'vs-seti-icon-theme.json');
const FONT_PATH = path.join(SETI_DIR, 'seti.woff');
const OUT_JS = path.join(ROOT_DIR, 'web', 'src', 'lib', 'setiFileIconTheme.generated.js');
const OUT_FONT = path.join(ROOT_DIR, 'web', 'public', 'vs-icons', 'seti.woff');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function normalizeKey(value) {
  return String(value || '').trim().replace(/\\/g, '/').toLowerCase();
}

function extensionKey(extension) {
  return normalizeKey(extension).replace(/^\.+/u, '');
}

function addIfMissing(target, key, iconId) {
  if (!key || !iconId || target[key]) return;
  target[key] = iconId;
}

function collectLanguageContributions(theme) {
  const fileExtensions = {};
  const fileNames = {};
  const filePatterns = [];

  for (const entry of fs.readdirSync(EXTENSIONS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const packagePath = path.join(EXTENSIONS_DIR, entry.name, 'package.json');
    if (!fs.existsSync(packagePath)) continue;
    let packageJson;
    try {
      packageJson = readJson(packagePath);
    } catch {
      continue;
    }

    for (const language of packageJson.contributes?.languages || []) {
      const iconId = theme.languageIds?.[language.id];
      if (!iconId) continue;
      for (const extension of language.extensions || []) {
        addIfMissing(fileExtensions, extensionKey(extension), iconId);
      }
      for (const fileName of language.filenames || []) {
        addIfMissing(fileNames, normalizeKey(fileName), iconId);
      }
      for (const pattern of language.filenamePatterns || []) {
        const normalizedPattern = normalizeKey(pattern);
        if (!normalizedPattern) continue;
        filePatterns.push([normalizedPattern, iconId]);
      }
    }
  }

  return { fileExtensions, fileNames, filePatterns };
}

function sortedObject(obj) {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)));
}

function jsString(value) {
  return JSON.stringify(value);
}

function fontCharacterCode(value) {
  const text = String(value || '');
  const escaped = text.match(/^\\([0-9a-f]{4,6})$/iu);
  if (escaped) return Number.parseInt(escaped[1], 16);
  return text.codePointAt(0) || 0xe023;
}

function iconDefinitionsSource(definitions) {
  const lines = Object.entries(sortedObject(definitions)).map(([id, def]) => {
    const glyphCode = fontCharacterCode(def.fontCharacter);
    const color = def.fontColor || '#d4d7d6';
    return `  ${jsString(id)}: [String.fromCodePoint(0x${glyphCode.toString(16)}), ${jsString(color)}],`;
  });
  return `Object.freeze({\n${lines.join('\n')}\n})`;
}

function idMapSource(obj) {
  const lines = Object.entries(sortedObject(obj)).map(([key, id]) => {
    return `  ${jsString(key)}: ${jsString(id)},`;
  });
  return `Object.freeze({\n${lines.join('\n')}\n})`;
}

function patternListSource(patterns) {
  const unique = new Map();
  for (const [pattern, iconId] of patterns) {
    if (!unique.has(pattern)) unique.set(pattern, iconId);
  }
  const lines = Array.from(unique.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([pattern, iconId]) => `  [${jsString(pattern)}, ${jsString(iconId)}],`);
  return `Object.freeze([\n${lines.join('\n')}\n])`;
}

function main() {
  if (!fs.existsSync(THEME_PATH)) {
    throw new Error(`VS Code Seti icon theme not found: ${THEME_PATH}`);
  }
  if (!fs.existsSync(FONT_PATH)) {
    throw new Error(`VS Code Seti icon font not found: ${FONT_PATH}`);
  }

  const theme = readJson(THEME_PATH);
  const language = collectLanguageContributions(theme);
  const fileExtensions = {
    ...language.fileExtensions,
    ...Object.fromEntries(
      Object.entries(theme.fileExtensions || {}).map(([key, value]) => [extensionKey(key), value]),
    ),
  };
  const fileNames = {
    ...language.fileNames,
    ...Object.fromEntries(
      Object.entries(theme.fileNames || {}).map(([key, value]) => [normalizeKey(key), value]),
    ),
  };

  const source = `// Generated by scripts/generate_seti_file_icon_theme.mjs from VS Code's built-in Seti icon theme.\n` +
    `// Do not edit by hand.\n\n` +
    `export const SETI_DEFAULT_FILE_ICON_ID = ${jsString(theme.file || '_default')};\n\n` +
    `export const SETI_ICON_DEFINITIONS = ${iconDefinitionsSource(theme.iconDefinitions || {})};\n\n` +
    `export const SETI_FILE_EXTENSION_ICON_IDS = ${idMapSource(fileExtensions)};\n\n` +
    `export const SETI_FILE_NAME_ICON_IDS = ${idMapSource(fileNames)};\n\n` +
    `export const SETI_FILE_PATTERN_ICON_IDS = ${patternListSource(language.filePatterns)};\n`;

  fs.mkdirSync(path.dirname(OUT_JS), { recursive: true });
  fs.writeFileSync(OUT_JS, source, 'utf8');
  fs.mkdirSync(path.dirname(OUT_FONT), { recursive: true });
  fs.copyFileSync(FONT_PATH, OUT_FONT);

  console.log(
    `Generated ${Object.keys(theme.iconDefinitions || {}).length} Seti definitions, ` +
    `${Object.keys(fileExtensions).length} extension mappings, ` +
    `${Object.keys(fileNames).length} filename mappings, and ` +
    `${language.filePatterns.length} filename patterns.`,
  );
}

main();
