from common import page, section, code, table, note

PAGES = {
"reference": page("按使用入口查找常用快捷键、命令与数据位置。具体可用项以当前安装的菜单和 /help 为准。", [
    section("shortcuts", "快捷键",
        table(["入口", "按键", "作用"], [["桌面 / Web 输入框", "<kbd>Enter</kbd>", "空闲时发送；运行时按当前状态排队。"], ["桌面 / Web 输入框", "<kbd>Shift+Enter</kbd>", "换行。"], ["桌面文件编辑器", "<kbd>Ctrl+S</kbd>", "保存当前可编辑文件。"], ["桌面终端停靠区", "<kbd>Ctrl+&#96;</kbd>", "显示或隐藏底部终端。"], ["TUI", "<kbd>Esc</kbd>", "等待时中断、退出 Shell 模式或拒绝当前确认。"], ["TUI", "<kbd>Ctrl+C</kbd>", "第一次清空输入并提示，1 秒内再次按下退出。"], ["TUI", "<kbd>Ctrl+O</kbd>", "全局展开或折叠工具结果。"], ["TUI", "<kbd>Ctrl+E</kbd>", "聚焦工具时切换该结果展开；否则移动到输入末尾。"], ["TUI", "<kbd>Ctrl+P</kbd>", "空闲普通输入状态切换权限；菜单或历史状态按对应导航处理。"], ["@ 候选菜单", "<kbd>↑</kbd> / <kbd>↓</kbd>、<kbd>Enter</kbd>", "选择并引用文件或文件夹。"], ["@ 候选菜单", "<kbd>Tab</kbd> / <kbd>→</kbd>", "进入选中的文件夹。"]]),
        '''<p>按键取决于焦点和当前模式。浏览器、操作系统或终端软件可能拦截组合键；遇到冲突优先使用可见按钮或菜单。本文档自身的 Ctrl+K 搜索快捷键不代表 ACECode 产品的同名操作。</p>'''),
    section("commands", "斜杠命令",
        table(["命令", "用途与范围"], [["<code>/help</code>", "查看当前注册的可用命令。"], ["<code>/model</code>", "模型选择；带名称可切换预设，TUI 支持 --cwd、--default 范围。"], ["<code>/mode</code>", "查看或切换权限模式。"], ["<code>/config</code>", "打开设置；/config show 查看文本概要。"], ["<code>/tokens</code>", "查看会话 token 用量。"], ["<code>/compact</code>", "调用模型压缩当前上下文。"], ["<code>/init</code>", "分析项目并生成或改进项目规则。"], ["<code>/resume</code>", "TUI 恢复历史会话。"], ["<code>/rewind</code>、<code>/checkpoint</code>", "TUI 打开回退选择器；代码恢复取决于检查点可用性。"], ["<code>/fork</code>", "TUI 从用户回合选择分叉，按选择器确认范围。"], ["<code>/archive</code>", "归档当前会话并开始新的对话状态。"], ["<code>/clear</code>、<code>/new</code>", "清理当前对话状态，开始新一段工作。"], ["<code>/side 问题</code>、<code>/btw 问题</code>", "独立的一次旁支问答，不调用工具。"], ["<code>/turn 补充说明</code>", "中断当前轮并发送指导；与排队卡片的插话时机不同。"], ["<code>/skills</code>、<code>/mcp</code>", "查看或管理技能与 MCP；带参数执行相应子命令。"], ["<code>/tools</code>、<code>/hooks</code>、<code>/connectors</code>", "打开对应能力管理入口。"], ["<code>/lsp</code>", "查看语言服务器状态。"], ["<code>/memory</code>", "列出、查看、编辑、遗忘或重载持久记忆。"], ["<code>/tasks</code>", "TUI 管理后台子任务。"], ["<code>/proxy</code>", "检查有效代理及临时覆盖状态。"], ["<code>/rc</code>、<code>/remote-control</code>", "激活已配置的默认渠道；show 查看，off 解绑。"], ["<code>/exit</code>", "退出 TUI。"]]),
        '''<p>不同入口的管理命令可能打开界面或返回文本，不能把 TUI 选择器当作所有前端都有的窗口。桌面/Web 在命令菜单中选择后仍需提交。技能也可能注册自己的斜杠入口，以当前发现的名称为准。</p>'''),
    section("arguments", "命令行参数",
        table(["命令或参数", "用途"], [["<code>acecode</code>", "在当前目录打开交互式 TUI。"], ["<code>acecode configure</code>", "初次配置或重新配置。"], ["<code>acecode --version</code>", "显示版本。"], ["<code>acecode -r</code>", "打开 TUI 历史会话选择。"], ["<code>acecode --resume [ID]</code>", "TUI 恢复最近会话或指定会话；print 模式必须带 ID。"], ["<code>acecode -p \"提示\"</code>", "执行无界面单轮任务。"], ["<code>--output-format text|json|stream-json</code>", "选择 print 模式输出格式。"], ["<code>--model NAME</code>", "选择已保存预设。"], ["<code>--permission-mode MODE</code>", "print 模式支持 default、accept-edits、plan、yolo。"], ["<code>--max-turns N</code>", "print 模式的智能体循环上限。"], ["<code>--session-id ID</code>", "指定新会话 ID。"], ["<code>-c</code>、<code>--continue</code>", "print 模式继续当前目录最近会话。"], ["<code>--list-tools</code>、<code>--list-skills</code>、<code>--list-mcp</code>", "只列出可发现能力。"], ["<code>--enable-skills 名称</code>、<code>--enable-mcp 名称</code>", "为 print 模式显式开启扩展。"], ["<code>--disable-tools 名称</code>", "为 print 模式禁用指定工具。"], ["<code>acecode daemon [start|status|stop]</code>", "独立后台管理。"], ["<code>acecode daemon --foreground</code>", "前台运行后台服务。"], ["<code>acecode daemon --cwd=路径 --port=端口</code>", "指定独立后台的起始工作目录与端口。"], ["<code>acecode upgrade</code>", "按已配置更新源执行自更新。"]]),
        '''<p>完整 print 参数运行 <code>acecode -p --help</code>。危险启动参数 <code>--yolo</code> / <code>--dangerous</code> 会绕过权限与路径检查，不作为排错默认步骤。查看脚本示例及退出码，参见 <a href="cli.html">CLI</a>。</p>'''),
    section("data", "本地配置和数据",
        '''<p>下面的路径相对于个人数据目录 <code>~/.acecode/</code>；Windows 为 <code>%USERPROFILE%/.acecode/</code>。Windows 服务另用 <code>%PROGRAMDATA%/acecode/</code>，远端进程使用远端身份的目录。</p>''',
        table(["路径", "内容"], [["<code>config.json</code>", "全局配置、模型连接与扩展定义，可能包含凭据。"], ["<code>config-backups/</code>", "有效配置快照和损坏配置备份，也可能含凭据。"], ["<code>projects/</code>", "按项目范围保存的会话、元数据和输入历史等记录。"], ["<code>skills/</code>", "用户技能；还可读取其他已启用根目录。"], ["<code>memory/</code>", "MEMORY.md 索引与记忆条目。"], ["<code>hooks.json</code>", "用户级 Hooks 定义。"], ["<code>logs/</code>", "按运行方式与日期保存的日志。"], ["<code>run/</code>", "独立后台的 PID、端口、GUID、心跳和 Token。"], ["<code>run/desktop-shared/</code>", "桌面托管后台的独立运行身份。"]]),
        '''<p>项目规则和项目技能可能保存在仓库本身。TUI 的 acecode.log 位于启动工作目录，不在上述 logs 目录。Git 工作树路径以任务实际记录为准。</p><p>备份前先结束相关写入，并同时考虑会话数据与实际项目文件。不要只备份 Markdown 导出就假定能够完整恢复，也不要在运行时随意删除身份文件或数据库。卸载与保留数据见<a href="update-uninstall.html">更新与卸载</a>。</p>''')
], ["docs/user-manual.md", "src/commands/builtin_commands.cpp", "src/headless/headless_options.cpp", "src/utils/paths.cpp", "docs/daemon-api.md", "src/memory/memory_paths.cpp"]),
}
