# winpty: Windows 10 < 1809(无 ConPTY)的完整终端体验兜底。
# 设计:openspec/changes/add-console-dock(design.md D3/D4)。
#
# 上游(rprichard/winpty)不是 CMake 工程(gyp + Makefile + vcbuild.bat),
# 这里按 src/winpty.gyp 的源文件清单手工定义两个 target:
#   - winpty_static : libwinpty 客户端静态库,链进 acecode_testable
#   - winpty-agent  : 独立 agent 可执行文件(挂隐藏 console 抓屏翻译 VT),
#                     运行时必须以磁盘文件存在 — 嵌入主程序、首次使用时
#                     释放到 <data_dir>/bin/
#
# 与上游的两处刻意偏离:
#   1. 不编译上游 libwinpty/AgentLocation.cc,由
#      src/web/pty/winpty_agent_location.cpp 提供同签名 findAgentProgram(),
#      支持进程级 agent 路径覆盖(上游硬编码"当前模块同目录",静态链接时
#      即 acecode.exe 同目录 — 安装目录通常不可写,无法释放 agent)。
#   2. WINPTY_API 静态适配:上游只有 dllexport/dllimport 两态。对库与
#      消费方统一 PUBLIC 定义 COMPILING_WINPTY_DLL,静态链接下 dllexport
#      仅在 exe 导出表多留几个符号,无运行时影响。

if(NOT WIN32)
    return()
endif()

include(FetchContent)

FetchContent_Declare(
    winpty_upstream
    GIT_REPOSITORY https://github.com/rprichard/winpty
    GIT_TAG        0.4.3
)
FetchContent_MakeAvailable(winpty_upstream)

set(WINPTY_SRC "${winpty_upstream_SOURCE_DIR}/src")

# 上游 UpdateGenVersion.bat 在构建期生成 gen/GenVersion.h;CMake 侧直接生成
# 固定内容(版本号与 GIT_TAG 对齐,commit 写 tag 名即可)。
set(WINPTY_GEN_DIR "${CMAKE_BINARY_DIR}/generated/winpty-gen")
file(MAKE_DIRECTORY "${WINPTY_GEN_DIR}")
file(WRITE "${WINPTY_GEN_DIR}/GenVersion.h"
    "// AUTO-GENERATED by cmake/acecode_winpty.cmake\n"
    "const char GenVersion_Version[] = \"0.4.3\";\n"
    "const char GenVersion_Commit[] = \"tag-0.4.3\";\n"
)

# 两个 target 共用的 shared/ 源(gyp 两份清单的并集裁剪:agent 需要全部,
# libwinpty 不需要的由链接器丢弃 — 静态库按需取目标文件,无体积代价)。
set(WINPTY_SHARED_SOURCES
    ${WINPTY_SRC}/shared/BackgroundDesktop.cc
    ${WINPTY_SRC}/shared/Buffer.cc
    ${WINPTY_SRC}/shared/DebugClient.cc
    ${WINPTY_SRC}/shared/GenRandom.cc
    ${WINPTY_SRC}/shared/OwnedHandle.cc
    ${WINPTY_SRC}/shared/StringUtil.cc
    ${WINPTY_SRC}/shared/WindowsSecurity.cc
    ${WINPTY_SRC}/shared/WindowsVersion.cc
    ${WINPTY_SRC}/shared/WinptyAssert.cc
    ${WINPTY_SRC}/shared/WinptyException.cc
    ${WINPTY_SRC}/shared/WinptyVersion.cc
)

# ── libwinpty 静态库(客户端 API:winpty_open/spawn/conin_name/...) ──────
add_library(winpty_static STATIC
    ${WINPTY_SRC}/libwinpty/winpty.cc
    ${CMAKE_SOURCE_DIR}/src/web/pty/winpty_agent_location.cpp
    ${WINPTY_SHARED_SOURCES}
)
target_include_directories(winpty_static PUBLIC
    ${WINPTY_SRC}/include
    ${WINPTY_GEN_DIR}
)
# libwinpty 内部 header(LibWinptyException.h 等)给 agent_location 替换实现用。
target_include_directories(winpty_static PRIVATE
    ${WINPTY_SRC}/libwinpty
    ${WINPTY_SRC}
)
target_compile_definitions(winpty_static PUBLIC
    COMPILING_WINPTY_DLL    # 见文件头注释 2
)
target_compile_definitions(winpty_static PRIVATE
    UNICODE _UNICODE NOMINMAX _WIN32_WINNT=0x0501
)
target_link_libraries(winpty_static PUBLIC advapi32 user32)

# ── winpty-agent.exe(随包嵌入,运行时释放) ────────────────────────────
add_executable(winpty-agent
    ${WINPTY_SRC}/agent/Agent.cc
    ${WINPTY_SRC}/agent/AgentCreateDesktop.cc
    ${WINPTY_SRC}/agent/ConsoleFont.cc
    ${WINPTY_SRC}/agent/ConsoleInput.cc
    ${WINPTY_SRC}/agent/ConsoleInputReencoding.cc
    ${WINPTY_SRC}/agent/ConsoleLine.cc
    ${WINPTY_SRC}/agent/DebugShowInput.cc
    ${WINPTY_SRC}/agent/DefaultInputMap.cc
    ${WINPTY_SRC}/agent/EventLoop.cc
    ${WINPTY_SRC}/agent/InputMap.cc
    ${WINPTY_SRC}/agent/LargeConsoleRead.cc
    ${WINPTY_SRC}/agent/NamedPipe.cc
    ${WINPTY_SRC}/agent/Scraper.cc
    ${WINPTY_SRC}/agent/Terminal.cc
    ${WINPTY_SRC}/agent/Win32Console.cc
    ${WINPTY_SRC}/agent/Win32ConsoleBuffer.cc
    ${WINPTY_SRC}/agent/main.cc
    ${WINPTY_SHARED_SOURCES}
)
target_include_directories(winpty-agent PRIVATE
    ${WINPTY_SRC}/include
    ${WINPTY_SRC}
    ${WINPTY_GEN_DIR}
)
target_compile_definitions(winpty-agent PRIVATE
    UNICODE _UNICODE NOMINMAX _WIN32_WINNT=0x0501
    WINPTY_AGENT_ASSERT
)
target_link_libraries(winpty-agent PRIVATE advapi32 shell32 user32)

# 上游代码是 2017 年的 C++11 风格,MSVC 新工具链会有无害告警;不让它们
# 淹没 acecode 自己的告警输出。
if(MSVC)
    target_compile_options(winpty_static PRIVATE /W0)
    target_compile_options(winpty-agent PRIVATE /W0)
endif()

# ── agent.exe 嵌入(单文件分发):构建出的 winpty-agent.exe 转字节数组,
# 链进 winpty_static。WinptyBackend 首次使用时释放到 <data_dir>/bin/。
set(WINPTY_AGENT_EMBEDDED_CPP "${CMAKE_BINARY_DIR}/generated/winpty_agent_embedded.cpp")
add_custom_command(
    OUTPUT ${WINPTY_AGENT_EMBEDDED_CPP}
    COMMAND ${CMAKE_COMMAND}
        -DBIN2CPP_INPUT=$<TARGET_FILE:winpty-agent>
        -DBIN2CPP_OUTPUT=${WINPTY_AGENT_EMBEDDED_CPP}
        -DBIN2CPP_SYMBOL=winpty_agent
        -P ${CMAKE_SOURCE_DIR}/cmake/acecode_bin2cpp.cmake
    DEPENDS winpty-agent ${CMAKE_SOURCE_DIR}/cmake/acecode_bin2cpp.cmake
    COMMENT "Embedding winpty-agent.exe into winpty_static"
)
target_sources(winpty_static PRIVATE ${WINPTY_AGENT_EMBEDDED_CPP})
