# 显式路径写错时必须在 configure 阶段失败，不能让 REMOVE_ITEM 或源属性静默失效。
include_guard(GLOBAL)

function(acecode_require_sources context)
    if(NOT ARGN)
        message(FATAL_ERROR "${context}: source list is empty")
    endif()
    foreach(_source IN LISTS ARGN)
        if(_source MATCHES "\\$<")
            message(FATAL_ERROR "${context}: expected a literal source path: ${_source}")
        endif()
        get_filename_component(_absolute "${_source}" ABSOLUTE
            BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        if(NOT EXISTS "${_absolute}" OR IS_DIRECTORY "${_absolute}")
            message(FATAL_ERROR "${context}: source file does not exist: ${_absolute}")
        endif()
    endforeach()
endfunction()

function(acecode_set_source_define source)
    acecode_require_sources("source compile definition" "${source}")
    if(NOT ARGN)
        message(FATAL_ERROR "source compile definition: no definition for ${source}")
    endif()
    set_property(SOURCE "${source}" APPEND PROPERTY COMPILE_DEFINITIONS ${ARGN})
endfunction()

# 与 lint 共用 layers.tsv。P0-P2 显式允许映射表中的旧路径；P3 M2 删除
# ALLOW_LEGACY 后，旧分支重新带回 src/session/ 等路径会在 configure 时失败。
function(acecode_assert_known_roots)
    cmake_parse_arguments(PARSE_ARGV 0 _guard "ALLOW_LEGACY" "" "SOURCES")
    if(_guard_UNPARSED_ARGUMENTS OR NOT _guard_SOURCES)
        message(FATAL_ERROR "known source roots: expected a nonempty SOURCES list")
    endif()
    set(_policy "${CMAKE_SOURCE_DIR}/src/layers.tsv")
    acecode_require_sources("source layout policy" "${_policy}")
    file(STRINGS "${_policy}" _rows REGEX "^module\t")
    set(_known_paths)
    foreach(_row IN LISTS _rows)
        string(REPLACE "\t" ";" _columns "${_row}")
        list(GET _columns 1 _prefix)
        list(APPEND _known_paths "${_prefix}")
    endforeach()
    if(NOT _known_paths)
        message(FATAL_ERROR "source layout policy contains no module roots: ${_policy}")
    endif()
    if(_guard_ALLOW_LEGACY)
        set(_mapping "${CMAKE_SOURCE_DIR}/scripts/refactor/src_layout_map.tsv")
        acecode_require_sources("legacy source layout map" "${_mapping}")
        file(STRINGS "${_mapping}" _rows REGEX "^src/")
        foreach(_row IN LISTS _rows)
            string(REPLACE "\t" ";" _columns "${_row}")
            list(GET _columns 0 _old_path)
            list(APPEND _known_paths "${_old_path}")
        endforeach()
    endif()
    list(REMOVE_DUPLICATES _known_paths)
    foreach(_source IN LISTS _guard_SOURCES)
        get_filename_component(_absolute "${_source}" ABSOLUTE
            BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        file(RELATIVE_PATH _relative "${CMAKE_SOURCE_DIR}" "${_absolute}")
        set(_known FALSE)
        foreach(_path IN LISTS _known_paths)
            if(_path MATCHES "/$")
                string(FIND "${_relative}" "${_path}" _position)
                if(_position EQUAL 0)
                    set(_known TRUE)
                    break()
                endif()
            elseif(_relative STREQUAL _path)
                set(_known TRUE)
                break()
            endif()
        endforeach()
        if(NOT _known)
            message(FATAL_ERROR "source is outside known layout roots: ${_relative}")
        endif()
    endforeach()
endfunction()
