# 显式路径写错时必须在 configure 阶段失败，不能让 REMOVE_ITEM 或源属性静默失效。
include_guard(GLOBAL)

function(acecode_require_sources context)
    if(NOT ARGN)
        message(FATAL_ERROR "${context}: source list is empty")
    endif()
    foreach(_source IN LISTS ARGN)
        if(_source MATCHES "\\$<")
            message(FATAL_ERROR "${context}: expected a literal source path: ${_source}")
        endif()
        get_filename_component(_absolute "${_source}" ABSOLUTE
            BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        if(NOT EXISTS "${_absolute}" OR IS_DIRECTORY "${_absolute}")
            message(FATAL_ERROR "${context}: source file does not exist: ${_absolute}")
        endif()
    endforeach()
endfunction()

function(acecode_set_source_define source)
    acecode_require_sources("source compile definition" "${source}")
    if(NOT ARGN)
        message(FATAL_ERROR "source compile definition: no definition for ${source}")
    endif()
    set_property(SOURCE "${source}" APPEND PROPERTY COMPILE_DEFINITIONS ${ARGN})
endfunction()

# 与 lint 共用 layers.tsv。P0-P2 显式允许映射表中的旧路径；P3 M2 删除
# ALLOW_LEGACY 后，旧分支重新带回 src/domain/session/ 等路径会在 configure 时失败。
function(acecode_assert_known_roots)
    cmake_parse_arguments(PARSE_ARGV 0 _guard "ALLOW_LEGACY" "" "SOURCES")
    if(_guard_UNPARSED_ARGUMENTS OR NOT _guard_SOURCES)
        message(FATAL_ERROR "known source roots: expected a nonempty SOURCES list")
    endif()
    set(_policy "${CMAKE_SOURCE_DIR}/src/layers.tsv")
    acecode_require_sources("source layout policy" "${_policy}")
    file(STRINGS "${_policy}" _rows REGEX "^module\t")
    set(_known_paths)
    foreach(_row IN LISTS _rows)
        string(REPLACE "\t" ";" _columns "${_row}")
        list(GET _columns 1 _prefix)
        list(APPEND _known_paths "${_prefix}")
    endforeach()
    if(NOT _known_paths)
        message(FATAL_ERROR "source layout policy contains no module roots: ${_policy}")
    endif()
    if(_guard_ALLOW_LEGACY)
        set(_mapping "${CMAKE_SOURCE_DIR}/scripts/refactor/src_layout_map.tsv")
        acecode_require_sources("legacy source layout map" "${_mapping}")
        file(STRINGS "${_mapping}" _rows REGEX "^src/")
        foreach(_row IN LISTS _rows)
            string(REPLACE "\t" ";" _columns "${_row}")
            list(GET _columns 0 _old_path)
            list(APPEND _known_paths "${_old_path}")
        endforeach()
    endif()
    list(REMOVE_DUPLICATES _known_paths)
    foreach(_source IN LISTS _guard_SOURCES)
        get_filename_component(_absolute "${_source}" ABSOLUTE
            BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        file(RELATIVE_PATH _relative "${CMAKE_SOURCE_DIR}" "${_absolute}")
        set(_known FALSE)
        foreach(_path IN LISTS _known_paths)
            if(_path MATCHES "/$")
                string(FIND "${_relative}" "${_path}" _position)
                if(_position EQUAL 0)
                    set(_known TRUE)
                    break()
                endif()
            elseif(_relative STREQUAL _path)
                set(_known TRUE)
                break()
            endif()
        endforeach()
        if(NOT _known)
            message(FATAL_ERROR "source is outside known layout roots: ${_relative}")
        endif()
    endforeach()
endfunction()

# Primary production targets must own every active translation unit once.
# Smoke fixtures are separate consumers and are intentionally not passed here.
function(acecode_assert_primary_sources)
    cmake_parse_arguments(PARSE_ARGV 0 _guard "" "" "SOURCES;TARGETS;INACTIVE")
    if(_guard_UNPARSED_ARGUMENTS OR NOT _guard_SOURCES OR NOT _guard_TARGETS)
        message(FATAL_ERROR "primary source ownership: expected SOURCES and TARGETS")
    endif()
    foreach(_target IN LISTS _guard_TARGETS)
        if(NOT TARGET ${_target})
            message(FATAL_ERROR "primary source ownership: target missing: ${_target}")
        endif()
        get_target_property(_sources ${_target} SOURCES)
        get_target_property(_directory ${_target} SOURCE_DIR)
        foreach(_source IN LISTS _sources)
            if(_source MATCHES "\\$<")
                message(FATAL_ERROR "primary source ownership: use literal paths in ${_target}: ${_source}")
            endif()
            get_filename_component(_absolute "${_source}" ABSOLUTE BASE_DIR "${_directory}")
            string(SHA256 _key "${_absolute}")
            list(APPEND _owners_${_key} "${_target}")
        endforeach()
    endforeach()
    foreach(_source IN LISTS _guard_SOURCES)
        string(SHA256 _key "${_source}")
        set(_owners "${_owners_${_key}}")
        list(LENGTH _owners _count)
        if(_source IN_LIST _guard_INACTIVE)
            if(NOT _count EQUAL 0)
                message(FATAL_ERROR "inactive source is compiled by ${_owners}: ${_source}")
            endif()
        elseif(NOT _count EQUAL 1)
            message(FATAL_ERROR "primary source ownership: expected one owner, found ${_count} (${_owners}): ${_source}")
        endif()
    endforeach()
endfunction()

# Library order is a topological order; cross-layer back edges fail configure.
function(acecode_assert_layer_targets)
    cmake_parse_arguments(PARSE_ARGV 0 _guard "" "AGGREGATE" "TARGETS")
    foreach(_target IN LISTS _guard_TARGETS)
        get_target_property(_type ${_target} TYPE)
        if(NOT _type STREQUAL "STATIC_LIBRARY")
            message(FATAL_ERROR "layer target must be STATIC: ${_target} is ${_type}")
        endif()
        list(FIND _guard_TARGETS "${_target}" _rank)
        get_target_property(_links ${_target} LINK_LIBRARIES)
        foreach(_link IN LISTS _links)
            list(FIND _guard_TARGETS "${_link}" _dependency_rank)
            if(_dependency_rank GREATER_EQUAL _rank)
                message(FATAL_ERROR "layer link must point downward: ${_target} -> ${_link}")
            endif()
        endforeach()
    endforeach()
    get_target_property(_type ${_guard_AGGREGATE} TYPE)
    get_target_property(_sources ${_guard_AGGREGATE} SOURCES)
    if(NOT _type STREQUAL "INTERFACE_LIBRARY" OR _sources)
        message(FATAL_ERROR "${_guard_AGGREGATE} must be a source-free INTERFACE aggregate")
    endif()
endfunction()

function(acecode_assert_no_link_path target)
    set(_queue "${target}")
    set(_visited)
    while(_queue)
        list(POP_FRONT _queue _current)
        if(_current IN_LIST _visited OR NOT TARGET ${_current})
            continue()
        endif()
        list(APPEND _visited "${_current}")
        if(_current IN_LIST ARGN)
            message(FATAL_ERROR "forbidden link path from ${target} reaches ${_current}")
        endif()
        foreach(_property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(_links ${_current} ${_property})
            foreach(_link IN LISTS _links)
                if(_link MATCHES "^\\$<(LINK_ONLY|BUILD_INTERFACE):([^>]+)>$")
                    set(_link "${CMAKE_MATCH_2}")
                endif()
                if(TARGET ${_link})
                    list(APPEND _queue "${_link}")
                endif()
            endforeach()
        endforeach()
    endwhile()
endfunction()
