# script 模式(cmake -P)二进制转 C++ 字节数组。
# 用法:
#   cmake -DBIN2CPP_INPUT=<file> -DBIN2CPP_OUTPUT=<out.cpp> -DBIN2CPP_SYMBOL=<name>
#         -P acecode_bin2cpp.cmake
# 生成:
#   const unsigned char <name>_data[] = {...};
#   <name>_data() / <name>_size() 访问函数(声明见对应手写 .hpp)。
# 现用于把 winpty-agent.exe 嵌入主程序(cmake/acecode_winpty.cmake),首次
# 创建 winpty 会话时释放到 <data_dir>/bin/。

if(NOT BIN2CPP_INPUT OR NOT BIN2CPP_OUTPUT OR NOT BIN2CPP_SYMBOL)
    message(FATAL_ERROR "bin2cpp: BIN2CPP_INPUT/BIN2CPP_OUTPUT/BIN2CPP_SYMBOL are required")
endif()

file(READ "${BIN2CPP_INPUT}" _hex HEX)
string(REGEX REPLACE "(..)" "0x\\1," _arr "${_hex}")
string(LENGTH "${_hex}" _hexlen)
math(EXPR _len "${_hexlen} / 2")

file(WRITE "${BIN2CPP_OUTPUT}"
    "// AUTO-GENERATED by cmake/acecode_bin2cpp.cmake from ${BIN2CPP_INPUT}\n"
    "#include <cstddef>\n"
    "namespace acecode {\n"
    "static const unsigned char ${BIN2CPP_SYMBOL}_bytes[] = {${_arr}};\n"
    "const unsigned char* ${BIN2CPP_SYMBOL}_data() { return ${BIN2CPP_SYMBOL}_bytes; }\n"
    "std::size_t ${BIN2CPP_SYMBOL}_size() { return ${_len}; }\n"
    "} // namespace acecode\n"
)
